import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :animina, AniminaWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  exclude: [
    paths: ["/health"],
    hosts: ["localhost", "127.0.0.1"]
  ]

# ANIMINA is shut down: serve the farewell page everywhere and stop all
# background workers so no jobs run and no mails go out. The mail queue
# checkers are additionally forced off in runtime.exs. Remove this block
# (and those runtime.exs lines) to bring the platform back.
config :animina,
  shutdown_mode: true,
  start_unconfirmed_user_cleaner: false,
  start_scheduler: false,
  start_online_users_logger: false,
  start_session_tracker: false,
  start_ai_services: false,
  start_status_cache: false

# Sendmail adapter doesn't need an HTTP API client
config :swoosh, api_client: false, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
