defmodule Animina.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :is_in_waitlist, :boolean, default: false
    end
  end

  def down do
    alter table(:users) do
      remove :is_in_waitlist
    end
  end
end
