defmodule Animina.Repo.Migrations.AddPostResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:posts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :content, :text, null: false
      add :slug, :text, null: false
      add :title, :text, null: false
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :user_id,
          references(:users,
            column: :id,
            name: "posts_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create index(:posts, [:user_id])
  end

  def down do
    drop constraint(:posts, "posts_user_id_fkey")

    drop_if_exists index(:posts, [:user_id])

    drop table(:posts)
  end
end
