defmodule Animina.Repo.Migrations.AddPartnerGender do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :partner_gender, :text
    end
  end

  def down do
    alter table(:users) do
      remove :partner_gender
    end
  end
end
