defmodule Animina.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:credits, "credits_user_id_fkey")

    alter table(:credits) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "credits_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    execute("ALTER TABLE credits alter CONSTRAINT credits_user_id_fkey NOT DEFERRABLE")
  end

  def down do
    drop constraint(:credits, "credits_user_id_fkey")

    alter table(:credits) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "credits_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
