defmodule Animina.Repo.Migrations.AddPreapprovedCommunicationOnly do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :preapproved_communication_only, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:users) do
      remove :preapproved_communication_only
    end
  end
end
