defmodule Animina.Repo.Migrations.AddBookmarksCustomIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:bookmarks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :reason, :text, null: false

      add :owner_id,
          references(:users,
            column: :id,
            name: "bookmarks_owner_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "bookmarks_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create index(:bookmarks, [:owner_id, :reason])

    create index(:bookmarks, [:owner_id, :user_id])

    create index(:bookmarks, [:user_id])

    create index(:bookmarks, [:reason])

    create index(:bookmarks, [:owner_id])

    create unique_index(:bookmarks, [:user_id, :owner_id, :reason],
             name: "bookmarks_unique_bookmark_index"
           )
  end

  def down do
    drop_if_exists unique_index(:bookmarks, [:user_id, :owner_id, :reason],
                     name: "bookmarks_unique_bookmark_index"
                   )

    drop constraint(:bookmarks, "bookmarks_owner_id_fkey")

    drop constraint(:bookmarks, "bookmarks_user_id_fkey")

    drop_if_exists index(:bookmarks, [:owner_id])

    drop_if_exists index(:bookmarks, [:reason])

    drop_if_exists index(:bookmarks, [:user_id])

    drop_if_exists index(:bookmarks, [:owner_id, :user_id])

    drop_if_exists index(:bookmarks, [:owner_id, :reason])

    drop table(:bookmarks)
  end
end
