defmodule Animina.Repo.Migrations.AddBookmarksLastVisitAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bookmarks) do
      add :last_visit_at, :utc_datetime
    end
  end

  def down do
    alter table(:bookmarks) do
      remove :last_visit_at
    end
  end
end
