defmodule Animina.Repo.Migrations.AddPhoto do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :zip_code, :text, null: true
      modify :name, :text, null: false
      modify :username, :citext, null: false
    end

    create table(:photos, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :filename, :text, null: false
      add :original_filename, :text, null: false
      add :mime, :text, null: false
      add :size, :bigint, null: false
      add :ext, :text, null: false
      add :dimensions, :map
      add :error, :text
      add :error_state, :text
      add :state, :text, null: false, default: "pending_review"

      add :user_id,
          references(:users,
            column: :id,
            name: "photos_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:photos, "photos_user_id_fkey")

    drop table(:photos)

    alter table(:users) do
      modify :username, :citext, null: true
      modify :name, :text, null: true
      modify :zip_code, :text, null: false
    end
  end
end
