defmodule Animina.Repo.Migrations.MigrateResources7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:credits) do
      add :donor_id,
          references(:users,
            column: :id,
            name: "credits_donor_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:credits, "credits_donor_id_fkey")

    alter table(:credits) do
      remove :donor_id
    end
  end
end
