defmodule Animina.Repo.Migrations.MigrateResources16 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:users), :is_public, to: :is_private

    alter table(:users) do
      modify :is_private, :boolean, default: false
    end
  end

  def down do
    alter table(:users) do
      modify :is_public, :boolean, default: true
    end

    rename table(:users), :is_private, to: :is_public
  end
end
