defmodule Animina.Repo.Migrations.AddHeadline do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:headlines, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :subject, :text, null: false
      add :position, :bigint, null: false
      add :is_active, :boolean, default: true
    end

    create unique_index(:headlines, [:position], name: "headlines_unique_position_index")

    create unique_index(:headlines, [:subject], name: "headlines_unique_subject_index")
  end

  def down do
    drop_if_exists unique_index(:headlines, [:subject], name: "headlines_unique_subject_index")

    drop_if_exists unique_index(:headlines, [:position], name: "headlines_unique_position_index")

    drop table(:headlines)
  end
end
