defmodule Animina.Repo.Migrations.MigrateResources23 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :state, :text, null: false
    end

    create table(:reports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :state, :text, null: false
      add :accused_user_state, :text, null: false
      add :description, :text, null: false
      add :internal_memo, :text
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :accused_id,
          references(:users,
            column: :id,
            name: "reports_accused_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :accuser_id,
          references(:users,
            column: :id,
            name: "reports_accuser_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :admin_id,
          references(:users,
            column: :id,
            name: "reports_admin_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:reports, "reports_accused_id_fkey")

    drop constraint(:reports, "reports_accuser_id_fkey")

    drop constraint(:reports, "reports_admin_id_fkey")

    drop table(:reports)

    alter table(:users) do
      modify :state, :text, null: true
    end
  end
end
