defmodule Animina.Repo.Migrations.MigrateResources20 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:visit_log_entries, [:bookmark_id, :user_id],
                     name: "visit_log_entries_unique_visit_log_entry_index"
                   )
  end

  def down do
    create unique_index(:visit_log_entries, [:bookmark_id, :user_id],
             name: "visit_log_entries_unique_visit_log_entry_index"
           )
  end
end
