defmodule Animina.Repo.Migrations.AddTrueDefaultForLegalTermsAccepted do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :legal_terms_accepted, :boolean, null: true, default: false
      add :occupation, :text
    end
  end

  def down do
    alter table(:users) do
      remove :occupation
      modify :legal_terms_accepted, :boolean, null: false, default: nil
    end
  end
end
