defmodule Animina.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :minimum_partner_height, :bigint
      add :maximum_partner_height, :bigint
      add :minimum_partner_age, :bigint
      add :maximum_partner_age, :bigint
    end
  end

  def down do
    alter table(:users) do
      remove :maximum_partner_age
      remove :minimum_partner_age
      remove :maximum_partner_height
      remove :minimum_partner_height
    end
  end
end
