defmodule Animina.Repo.Migrations.MigrateResources17 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:photos) do
      add :tagged_at, :utc_datetime
    end
  end

  def down do
    alter table(:photos) do
      remove :tagged_at
    end
  end
end
