defmodule Animina.Repo.Migrations.AddLegalTermsAccepted do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :legal_terms_accepted, :boolean, null: false
    end
  end

  def down do
    alter table(:users) do
      remove :legal_terms_accepted
    end
  end
end
