defmodule Animina.Repo.Migrations.AddPhotoFlagable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:traits_flags) do
      add :photo_flagable, :boolean, default: false
    end

    execute """
    UPDATE traits_flags
SET photo_flagable = CASE
    WHEN traits_categories.name IN ('animals', 'sports', 'travels', 'favorite_destinations', 'at_home', 'creativity') THEN true
    ELSE false
END
FROM traits_categories
WHERE traits_flags.category_id = traits_categories.id;
    """
  end

  def down do
    alter table(:traits_flags) do
      remove :photo_flagable
    end
  end
end
