defmodule Animina.Repo.Migrations.MigrateResources9 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration
  drop table(:photo_tags)
  drop table(:photo_flag_tags)

end
