defmodule Animina.Repo.Migrations.MigrateResources26 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:visit_log_entries) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :created_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:users) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :created_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:user_roles) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :created_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:user_flags) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :created_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:traits_flags) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:traits_flag_translations) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:traits_category_translations) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:traits_categories) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:stories) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :created_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:roles) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :created_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:reports) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :created_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:reactions) do
      modify :created_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:potential_partners) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :created_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:posts) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :created_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:photos) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :created_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    create table(:optimized_photos, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :image_url, :text, null: false
      add :type, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "optimized_photos_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :photo_id,
          references(:photos,
            column: :id,
            name: "optimized_photos_photo_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    alter table(:messages) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :created_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:headlines) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:geo_data_cities) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:credits) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :created_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:bookmarks) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :created_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:bad_passwords) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end
  end

  def down do
    alter table(:bad_passwords) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
    end

    alter table(:bookmarks) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
      modify :created_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:credits) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
      modify :created_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:geo_data_cities) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
    end

    alter table(:headlines) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
    end

    alter table(:messages) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
      modify :created_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    drop constraint(:optimized_photos, "optimized_photos_user_id_fkey")

    drop constraint(:optimized_photos, "optimized_photos_photo_id_fkey")

    drop table(:optimized_photos)

    alter table(:photos) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
      modify :created_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:posts) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
      modify :created_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:potential_partners) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
      modify :created_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:reactions) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
      modify :created_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:reports) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
      modify :created_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:roles) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
      modify :created_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:stories) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
      modify :created_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:traits_categories) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
    end

    alter table(:traits_category_translations) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
    end

    alter table(:traits_flag_translations) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
    end

    alter table(:traits_flags) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
    end

    alter table(:user_flags) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
      modify :created_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:user_roles) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
      modify :created_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:users) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
      modify :created_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:visit_log_entries) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
      modify :created_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end
  end
end
