defmodule :"Elixir.Animina.Repo.Migrations.Relate photos to stories" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:stories) do
      modify :content, :text, null: true
    end

    alter table(:photos) do
      add :story_id,
          references(:stories,
            column: :id,
            name: "photos_story_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:photos, "photos_story_id_fkey")

    alter table(:photos) do
      remove :story_id
    end

    alter table(:stories) do
      modify :content, :text, null: false
    end
  end
end
