defmodule Animina.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :email_confirmed, :boolean, null: false
      add :disabled_by_platform_at, :utc_datetime
      add :disabled_by_user_at, :utc_datetime
      add :date_of_birth, :date, null: false
      add :subscribed_at, :utc_datetime, null: false
    end

    create unique_index(:users, [:username], name: "users_unique_username_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:username], name: "users_unique_username_index")

    alter table(:users) do
      remove :subscribed_at
      remove :date_of_birth
      remove :disabled_by_user_at
      remove :disabled_by_platform_at
      remove :email_confirmed
    end
  end
end