defmodule :"Elixir.Animina.Repo.Migrations.Add flagId userId index" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:user_interests, ["flag_id", "user_id"])
  end

  def down do
    drop_if_exists index(:user_interests, ["flag_id", "user_id"],
                     name: "user_interests_flag_id_user_id_index"
                   )
  end
end
