defmodule Animina.Repo.Migrations.AddUniqueMobilePhone do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:users, [:mobile_phone], name: "users_unique_mobile_phone_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:mobile_phone], name: "users_unique_mobile_phone_index")
  end
end
