defmodule Animina.Repo.Migrations.MigrateResources11 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :username, :text
    end

    alter table(:messages) do
      modify :receiver_id, :uuid, null: false
      modify :sender_id, :uuid, null: false
      modify :content, :text, null: false
    end
  end

  def down do
    alter table(:messages) do
      modify :content, :text, null: true
      modify :sender_id, :uuid, null: true
      modify :receiver_id, :uuid, null: true
    end

    alter table(:users) do
      modify :username, :citext
    end
  end
end
