defmodule Animina.Repo.Migrations.MigrateResources22 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :state, :text, default: "normal"
    end
  end

  def down do
    alter table(:users) do
      remove :state
    end
  end
end
