defmodule Animina.Repo.Migrations.MigrateResources19 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:visit_log_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :duration, :bigint, null: false
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :user_id,
          references(:users,
            column: :id,
            name: "visit_log_entries_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :bookmark_id,
          references(:bookmarks,
            column: :id,
            name: "visit_log_entries_bookmark_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:visit_log_entries, [:user_id, :bookmark_id])

    create unique_index(:visit_log_entries, [:user_id, :bookmark_id],
             name: "visit_log_entries_unique_visit_log_entry_index"
           )
  end

  def down do
    drop_if_exists unique_index(:visit_log_entries, [:user_id, :bookmark_id],
                     name: "visit_log_entries_unique_visit_log_entry_index"
                   )

    drop constraint(:visit_log_entries, "visit_log_entries_user_id_fkey")

    drop constraint(:visit_log_entries, "visit_log_entries_bookmark_id_fkey")

    drop_if_exists index(:visit_log_entries, [:user_id, :bookmark_id])

    drop table(:visit_log_entries)
  end
end
