defmodule :"Elixir.Animina.Repo.Migrations.Add position to user interests" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_interests) do
      add :position, :bigint, null: false
    end
  end

  def down do
    alter table(:user_interests) do
      remove :position
    end
  end
end
