#!/bin/bash
# Organize cropped avatar photos into male/female directories
# with avatar-dev-{firstname}.jpg naming for dev seeds

CROP_DIR="priv/static/images/seeds/avatars/incoming/cropped"
MALE_DIR="priv/static/images/seeds/avatars/male"
FEMALE_DIR="priv/static/images/seeds/avatars/female"

cd "$(dirname "$0")/.."

mkdir -p "$MALE_DIR" "$FEMALE_DIR"

echo "Copying female avatars..."
# FEMALES (47 unique)
cp "$CROP_DIR/ahmed-yameen-K-HhBxMhgr0-unsplash.jpg" "$FEMALE_DIR/avatar-dev-sabine.jpg"
cp "$CROP_DIR/albert-oliveira-sVV_a0iXgbg-unsplash.jpg" "$FEMALE_DIR/avatar-dev-nina.jpg"
cp "$CROP_DIR/alex-jiang-qjU29LwfevM-unsplash.jpg" "$FEMALE_DIR/avatar-dev-mei.jpg"
cp "$CROP_DIR/alex-perez-uGXEEwnvIkQ-unsplash.jpg" "$FEMALE_DIR/avatar-dev-claudia.jpg"
cp "$CROP_DIR/alexis-chloe-TYDkKEgc0Fg-unsplash.jpg" "$FEMALE_DIR/avatar-dev-amara.jpg"
cp "$CROP_DIR/ali-nejatian-LiDt156C76Q-unsplash.jpg" "$FEMALE_DIR/avatar-dev-ronja.jpg"
cp "$CROP_DIR/almos-bechtold-3402kvtHhOo-unsplash.jpg" "$FEMALE_DIR/avatar-dev-hannah.jpg"
cp "$CROP_DIR/andrey-k-equeiRhA8t0-unsplash.jpg" "$FEMALE_DIR/avatar-dev-svenja.jpg"
cp "$CROP_DIR/andrey-k-GtIC5TPxD_c-unsplash.jpg" "$FEMALE_DIR/avatar-dev-mia.jpg"
cp "$CROP_DIR/andrey-k-m9iVxSpgGes-unsplash.jpg" "$FEMALE_DIR/avatar-dev-johanna.jpg"
cp "$CROP_DIR/andrey-k-yK1Bt3vWsVo-unsplash.jpg" "$FEMALE_DIR/avatar-dev-nora.jpg"
cp "$CROP_DIR/anna-deli-IqzSHrVXTbE-unsplash.jpg" "$FEMALE_DIR/avatar-dev-vanessa.jpg"
cp "$CROP_DIR/atikh-bana-2c0midsQKe0-unsplash.jpg" "$FEMALE_DIR/avatar-dev-leonie.jpg"
cp "$CROP_DIR/averie-woodard-4nulm-JUYFo-unsplash.jpg" "$FEMALE_DIR/avatar-dev-sophie.jpg"
cp "$CROP_DIR/ben-scott-tWb7IsL9CnY-unsplash.jpg" "$FEMALE_DIR/avatar-dev-greta.jpg"
cp "$CROP_DIR/christina-wocintechchat-com-m-0Zx1bDv5BNY-unsplash.jpg" "$FEMALE_DIR/avatar-dev-jasmin.jpg"
cp "$CROP_DIR/connor-wilkins-2crxTr4jCkc-unsplash.jpg" "$FEMALE_DIR/avatar-dev-clara.jpg"
cp "$CROP_DIR/courtney-cook-TSZo17r3m0s-unsplash.jpg" "$FEMALE_DIR/avatar-dev-katharina.jpg"
cp "$CROP_DIR/daniil-lobachev-93BsHRWB1yQ-unsplash.jpg" "$FEMALE_DIR/avatar-dev-anja.jpg"
cp "$CROP_DIR/dmytro-suk-9_iWA6YQ-9U-unsplash.jpg" "$FEMALE_DIR/avatar-dev-eva.jpg"
cp "$CROP_DIR/ehsan-ahmadi-vsWy6nchcOs-unsplash.jpg" "$FEMALE_DIR/avatar-dev-birgit.jpg"
cp "$CROP_DIR/eli-defaria-25WM4IEnPIg-unsplash.jpg" "$FEMALE_DIR/avatar-dev-lina.jpg"
cp "$CROP_DIR/ethan-haddox-NTjSR3zYpsY-unsplash.jpg" "$FEMALE_DIR/avatar-dev-selina.jpg"
cp "$CROP_DIR/felipe-vera-fRw0ryWZ6vU-unsplash.jpg" "$FEMALE_DIR/avatar-dev-frieda.jpg"
cp "$CROP_DIR/fien-schelstraete-5hdkCZO7fPk-unsplash.jpg" "$FEMALE_DIR/avatar-dev-amelie.jpg"
cp "$CROP_DIR/giullianna-balza-R8qoHaEA0fY-unsplash.jpg" "$FEMALE_DIR/avatar-dev-tanja.jpg"
cp "$CROP_DIR/good-faces-xmSWVeGEnJw-unsplash.jpg" "$FEMALE_DIR/avatar-dev-fatou.jpg"
cp "$CROP_DIR/guillaume-bolduc-wnA05v1BaNo-unsplash.jpg" "$FEMALE_DIR/avatar-dev-marie.jpg"
cp "$CROP_DIR/hassan-khan-EGVccebWodM-unsplash.jpg" "$FEMALE_DIR/avatar-dev-layla.jpg"
cp "$CROP_DIR/houcine-ncib-B4TjXnI0Y2c-unsplash.jpg" "$FEMALE_DIR/avatar-dev-emma.jpg"
cp "$CROP_DIR/irene-strong--FOUPtqP-mY-unsplash.jpg" "$FEMALE_DIR/avatar-dev-julia.jpg"
cp "$CROP_DIR/irina-iriser-T9_NHo5d0pc-unsplash.jpg" "$FEMALE_DIR/avatar-dev-natasha.jpg"
cp "$CROP_DIR/jake-nackos-IF9TK5Uy-KI-unsplash.jpg" "$FEMALE_DIR/avatar-dev-daniela.jpg"
cp "$CROP_DIR/joe-gardner-N5GCRjEMboQ-unsplash.jpg" "$FEMALE_DIR/avatar-dev-kira.jpg"
cp "$CROP_DIR/kim-carpenter-IHIgnhLvz5Q-unsplash.jpg" "$FEMALE_DIR/avatar-dev-aisha.jpg"
cp "$CROP_DIR/ladislav-stercell-A0_dBWbBwvU-unsplash.jpg" "$FEMALE_DIR/avatar-dev-petra.jpg"
cp "$CROP_DIR/laura-adai-AF50O2MtgOU-unsplash.jpg" "$FEMALE_DIR/avatar-dev-lena.jpg"
cp "$CROP_DIR/lorenzo-costamagna-1Ei2qjy6KVs-unsplash.jpg" "$FEMALE_DIR/avatar-dev-carla.jpg"
cp "$CROP_DIR/maria-lysenko-s6ZorDw5RrI-unsplash.jpg" "$FEMALE_DIR/avatar-dev-anna.jpg"
cp "$CROP_DIR/michael-dam-mEZ3PoFGs_k-unsplash.jpg" "$FEMALE_DIR/avatar-dev-yuki.jpg"
cp "$CROP_DIR/natalie-heathcoat-QP1N1rK5QlA-unsplash.jpg" "$FEMALE_DIR/avatar-dev-teresa.jpg"
cp "$CROP_DIR/ospan-ali-_ZXdnKTHPGs-unsplash.jpg" "$FEMALE_DIR/avatar-dev-milena.jpg"
cp "$CROP_DIR/rachel-mcdermott-0fN7Fxv1eWA-unsplash.jpg" "$FEMALE_DIR/avatar-dev-franzi.jpg"
cp "$CROP_DIR/roberto-leone-iXJ3t8hZUCg-unsplash.jpg" "$FEMALE_DIR/avatar-dev-pia.jpg"
cp "$CROP_DIR/see-plus-39GcuxM6ehA-unsplash.jpg" "$FEMALE_DIR/avatar-dev-elif.jpg"
cp "$CROP_DIR/teodora-popa-photographer-swAffTYbnfQ-unsplash.jpg" "$FEMALE_DIR/avatar-dev-stella.jpg"
cp "$CROP_DIR/thibaut-santy-hlSX_jyf5ys-unsplash.jpg" "$FEMALE_DIR/avatar-dev-luisa.jpg"

echo "Copying male avatars..."
# MALES (48 unique)
cp "$CROP_DIR/abdullah-ali-1w9I6H4aftw-unsplash.jpg" "$MALE_DIR/avatar-dev-karim.jpg"
cp "$CROP_DIR/aditya-sethia-SuRT02HfjCM-unsplash.jpg" "$MALE_DIR/avatar-dev-raj.jpg"
cp "$CROP_DIR/alex-zeng-SPE-PolG3ZI-unsplash.jpg" "$MALE_DIR/avatar-dev-wei.jpg"
cp "$CROP_DIR/alyona-grishina-BBmi4nJjKk8-unsplash.jpg" "$MALE_DIR/avatar-dev-marko.jpg"
cp "$CROP_DIR/alyona-grishina-JQGxnrGOkEI-unsplash.jpg" "$MALE_DIR/avatar-dev-fynn.jpg"
cp "$CROP_DIR/andrei-damian-SPF4yEvlCEo-unsplash.jpg" "$MALE_DIR/avatar-dev-nico.jpg"
cp "$CROP_DIR/arshad-khan-q-S7-oKY--4-unsplash.jpg" "$MALE_DIR/avatar-dev-bjoern.jpg"
cp "$CROP_DIR/ayo-ogunseinde-sibVwORYqs0-unsplash.jpg" "$MALE_DIR/avatar-dev-samuel.jpg"
cp "$CROP_DIR/ben-o-bro-C5XyLljkMrY-unsplash.jpg" "$MALE_DIR/avatar-dev-torsten.jpg"
cp "$CROP_DIR/christian-buehner-DItYlc26zVI-unsplash.jpg" "$MALE_DIR/avatar-dev-florian.jpg"
cp "$CROP_DIR/christian-buehner-zYD6ou1Qj10-unsplash.jpg" "$MALE_DIR/avatar-dev-thomas.jpg"
cp "$CROP_DIR/christopher-luther-awco4Ls1X0o-unsplash.jpg" "$MALE_DIR/avatar-dev-joerg.jpg"
cp "$CROP_DIR/craig-mckay-jmURdhtm7Ng-unsplash.jpg" "$MALE_DIR/avatar-dev-viktor.jpg"
cp "$CROP_DIR/curtis-powell-3mMvCsW6ZYs-unsplash.jpg" "$MALE_DIR/avatar-dev-david.jpg"
cp "$CROP_DIR/dani-SzHsiYO6pZE-unsplash.jpg" "$MALE_DIR/avatar-dev-lukas.jpg"
cp "$CROP_DIR/daniil-onischenko-GHf1Dw6oCEc-unsplash.jpg" "$MALE_DIR/avatar-dev-anton.jpg"
cp "$CROP_DIR/denis-agati--5Vl9oimYlU-unsplash.jpg" "$MALE_DIR/avatar-dev-stefan.jpg"
cp "$CROP_DIR/ellery-sterling-CBtjtyXc2ls-unsplash.jpg" "$MALE_DIR/avatar-dev-klaus.jpg"
cp "$CROP_DIR/emmanuel-yeboah-okine-DzAFv1iVMGg-unsplash.jpg" "$MALE_DIR/avatar-dev-emmanuel.jpg"
cp "$CROP_DIR/erik-lucatero-d2MSDujJl2g-unsplash.jpg" "$MALE_DIR/avatar-dev-finn.jpg"
cp "$CROP_DIR/erik-mclean-06vpBIHmiYc-unsplash.jpg" "$MALE_DIR/avatar-dev-henning.jpg"
cp "$CROP_DIR/fabio-henning-mMTqXCM1pYU-unsplash.jpg" "$MALE_DIR/avatar-dev-robin.jpg"
cp "$CROP_DIR/gabriel-silverio-u3WmDyKGsrY-unsplash.jpg" "$MALE_DIR/avatar-dev-rafael.jpg"
cp "$CROP_DIR/irene-strong-TMt3JGoVlng-unsplash.jpg" "$MALE_DIR/avatar-dev-tim.jpg"
cp "$CROP_DIR/jack-finnigan-rriAI0nhcbc-unsplash.jpg" "$MALE_DIR/avatar-dev-philipp.jpg"
cp "$CROP_DIR/jassir-jonis-QWa0TIUW638-unsplash.jpg" "$MALE_DIR/avatar-dev-tarek.jpg"
cp "$CROP_DIR/jeremy-bishop-ctAsm_deVVk-unsplash.jpg" "$MALE_DIR/avatar-dev-moritz.jpg"
cp "$CROP_DIR/joao-uCnJqu9ubm0-unsplash.jpg" "$MALE_DIR/avatar-dev-wolfgang.jpg"
cp "$CROP_DIR/jurica-koletic-efqnM0zWh54-unsplash.jpg" "$MALE_DIR/avatar-dev-jan.jpg"
cp "$CROP_DIR/kelvin-vega-Sfe-CMqHh7A-unsplash.jpg" "$MALE_DIR/avatar-dev-diego.jpg"
cp "$CROP_DIR/ludvig-wiese-d-MfHM-jHwc-unsplash.jpg" "$MALE_DIR/avatar-dev-ludwig.jpg"
cp "$CROP_DIR/mathieu-improvisato-OhM8DcFLzy8-unsplash.jpg" "$MALE_DIR/avatar-dev-matthias.jpg"
cp "$CROP_DIR/midas-hofstra-tidSLv-UaNs-unsplash.jpg" "$MALE_DIR/avatar-dev-erik.jpg"
cp "$CROP_DIR/misael-silvera-5CSRi249CQk-unsplash.jpg" "$MALE_DIR/avatar-dev-carlos.jpg"
cp "$CROP_DIR/nartan-buyukyildiz-qo1SX1HDPnM-unsplash.jpg" "$MALE_DIR/avatar-dev-osman.jpg"
cp "$CROP_DIR/nathan-dumlao-fghYlu1ec2U-unsplash.jpg" "$MALE_DIR/avatar-dev-sven.jpg"
cp "$CROP_DIR/nrd-y3kC_7Qhmjk-unsplash.jpg" "$MALE_DIR/avatar-dev-felix.jpg"
cp "$CROP_DIR/pacha-shot-s-d0peGya6R5Y-unsplash.jpg" "$MALE_DIR/avatar-dev-ben.jpg"
cp "$CROP_DIR/podmatch-UpiF461EAHU-unsplash.jpg" "$MALE_DIR/avatar-dev-patrick.jpg"
cp "$CROP_DIR/prince-akachi-4Yv84VgQkRM-unsplash.jpg" "$MALE_DIR/avatar-dev-kwame.jpg"
cp "$CROP_DIR/reza-biazar-eSjmZW97cH8-unsplash.jpg" "$MALE_DIR/avatar-dev-hamid.jpg"
cp "$CROP_DIR/riccardo-pitzalis-5ja5MkgoGAU-unsplash.jpg" "$MALE_DIR/avatar-dev-marco.jpg"
cp "$CROP_DIR/sanjoy-saha-CW1MZc-8jww-unsplash.jpg" "$MALE_DIR/avatar-dev-arjun.jpg"
cp "$CROP_DIR/sedk-mahmoud-cBtrsNMxB14-unsplash.jpg" "$MALE_DIR/avatar-dev-samir.jpg"
cp "$CROP_DIR/sergio-de-paula-c_GmwfHBDzk-unsplash.jpg" "$MALE_DIR/avatar-dev-gabriel.jpg"
cp "$CROP_DIR/taylor-8Vt2haq8NSQ-unsplash.jpg" "$MALE_DIR/avatar-dev-leon.jpg"
cp "$CROP_DIR/vinicius-amnx-amano-0NCjjD0zGnw-unsplash.jpg" "$MALE_DIR/avatar-dev-alessandro.jpg"
cp "$CROP_DIR/warren-VVEwJJRRHgk-unsplash.jpg" "$MALE_DIR/avatar-dev-daniel.jpg"

echo ""
echo "Done! Copied $(ls "$FEMALE_DIR" | wc -l | tr -d ' ') female + $(ls "$MALE_DIR" | wc -l | tr -d ' ') male avatars."
