name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**.exs'
      - '**.ex'
      - '**/mix.lock'
      - 'priv/repo/migrations/**/*'
      - 'priv/repo/seeds.exs'
      - '.github/workflows/*'

jobs:
  test:
    runs-on: ubuntu-20.04
    name: OTP ${{ matrix.otp }} / Elixir ${{ matrix.elixir }}
    strategy:
      matrix:
        otp: ['26.2.5']
        elixir: ['1.16.3']
        include:
          - otp: '26.2.5'
            elixir: '1.16.3'

    services:
      db:
        image: postgres:13-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: animina_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.mix
            ~/.hex
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
          mix compile

      - name: Restore database from cache
        id: restore-db
        uses: actions/cache@v3
        with:
          path: db_dump.sql
          key: ${{ runner.os }}-db-${{ hashFiles('priv/repo/migrations/**/*', 'priv/repo/seeds.exs') }}
          restore-keys: |
            ${{ runner.os }}-db-

      - name: Setup database
        if: steps.restore-db.outputs.cache-hit != 'true'
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: animina_test
        run: |
          mix ecto.create
          mix ecto.migrate
          mix run priv/repo/seeds.exs
          pg_dump -Fc -f db_dump.sql -U postgres animina_test

      - name: Restore database from dump
        if: steps.restore-db.outputs.cache-hit == 'true'
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: animina_test
        run: |
          pg_restore -U postgres -d animina_test db_dump.sql

      - name: Cache database dump
        if: steps.restore-db.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: db_dump.sql
          key: ${{ runner.os }}-db-${{ hashFiles('priv/repo/migrations/**/*', 'priv/repo/seeds.exs') }}

      - name: Run tests
        env:
          MIX_ENV: test
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: animina_test
        run: mix test

      - name: Run Credo
        run: mix credo --strict
